/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package edu.kit.ibds.mowidi.mobile;

public final class R {
    public static final class array {
        /**  Access rights spinner 
 Access rights spinner 
 Access rights spinner 
         */
        public static final int access_rights=0x7f060000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int alert_dialog_icon=0x7f020000;
        public static final int launcher_icon=0x7f020001;
        public static final int opt_help_icon=0x7f020002;
        public static final int opt_info=0x7f020003;
        public static final int opt_info_icon=0x7f020004;
        public static final int opt_quit=0x7f020005;
        public static final int opt_quit_icon=0x7f020006;
        public static final int opt_settings=0x7f020007;
        public static final int opt_settings_icon=0x7f020008;
        public static final int pc_icon=0x7f020009;
        public static final int status_icon=0x7f02000a;
    }
    public static final class id {
        public static final int about_developed_label=0x7f080020;
        public static final int about_version=0x7f08001f;
        public static final int about_version_label=0x7f08001e;
        public static final int about_website=0x7f080021;
        public static final int b_ok=0x7f08002f;
        public static final int con_settings_accessRights_label=0x7f080005;
        public static final int con_settings_actualName_label=0x7f080000;
        public static final int con_settings_check=0x7f080007;
        public static final int con_settings_givenPcName_label=0x7f080002;
        public static final int con_settings_name=0x7f080001;
        public static final int con_settings_nameEdit=0x7f080003;
        public static final int con_settings_okButton=0x7f080004;
        public static final int con_settings_spinner=0x7f080006;
        public static final int connect_accessRights_label=0x7f08000a;
        public static final int connect_autoCheck=0x7f08000c;
        public static final int connect_hashcode=0x7f080009;
        public static final int connect_hashcode_label=0x7f080008;
        public static final int connect_okButton=0x7f08000d;
        public static final int connect_spinner=0x7f08000b;
        public static final int disconnect_noButton=0x7f080011;
        public static final int disconnect_root=0x7f08000e;
        public static final int disconnect_text=0x7f08000f;
        public static final int disconnect_yesButton=0x7f080010;
        public static final int help_conSettings_label=0x7f080018;
        public static final int help_conSettings_text=0x7f080019;
        public static final int help_connect_label=0x7f080015;
        public static final int help_connect_text1=0x7f080016;
        public static final int help_connect_text2=0x7f080017;
        public static final int help_disconnect_label=0x7f08001a;
        public static final int help_disconnect_text=0x7f08001b;
        public static final int help_settings_label=0x7f080012;
        public static final int help_settings_text1=0x7f080013;
        public static final int help_settings_text2=0x7f080014;
        public static final int hint_text=0x7f08001c;
        public static final int main_empty=0x7f080022;
        public static final int main_icon=0x7f080023;
        public static final int main_pcName=0x7f080024;
        public static final int main_pcState=0x7f080025;
        public static final int opt_help=0x7f080038;
        public static final int opt_info=0x7f080037;
        public static final int opt_quit=0x7f080039;
        public static final int opt_settings=0x7f080036;
        public static final int pc_settings_actualName_label=0x7f080026;
        public static final int pc_settings_check=0x7f08002c;
        public static final int pc_settings_editButton=0x7f08002a;
        public static final int pc_settings_givenPcName_label=0x7f080028;
        public static final int pc_settings_name=0x7f080027;
        public static final int pc_settings_name_edit=0x7f080029;
        public static final int pc_settings_spinner=0x7f08002b;
        public static final int rb_lang_checked=0x7f080032;
        public static final int settings_langGroup_label=0x7f080031;
        public static final int settings_languageAuto=0x7f080033;
        public static final int settings_languageEng=0x7f080035;
        public static final int settings_languageGer=0x7f080034;
        public static final int settings_language_label=0x7f080030;
        public static final int settings_mobileName_edit=0x7f08002e;
        public static final int settings_mobileName_label=0x7f08002d;
        public static final int thanks_text=0x7f08001d;
    }
    public static final class layout {
        public static final int con_settings=0x7f030000;
        public static final int connect=0x7f030001;
        public static final int connect_dialog=0x7f030002;
        public static final int disconnect_dialog=0x7f030003;
        public static final int help_dialog=0x7f030004;
        public static final int info_dialog=0x7f030005;
        public static final int main=0x7f030006;
        public static final int main_item=0x7f030007;
        public static final int pc_settings_dialog=0x7f030008;
        public static final int settings=0x7f030009;
    }
    public static final class menu {
        public static final int options_menu=0x7f070000;
    }
    public static final class raw {
        public static final int device_desc=0x7f040000;
    }
    public static final class string {
        public static final int access_rights_prompt=0x7f050014;
        /**  MainView 
 MainView 
 MainView 
         */
        public static final int app_name=0x7f050000;
        public static final int auto_connect=0x7f050015;
        public static final int automatic=0x7f050007;
        public static final int cancel=0x7f050017;
        public static final int conSettings_label=0x7f050027;
        public static final int conSettings_text=0x7f050028;
        /**  Connect Dialog 
 Connect Dialog 
 Connect Dialog 
         */
        public static final int connect=0x7f050012;
        public static final int connect_label=0x7f050024;
        public static final int connect_text1=0x7f050025;
        public static final int connect_text2=0x7f050026;
        public static final int connected=0x7f050002;
        public static final int developed_label=0x7f05001f;
        public static final int disconnect_label=0x7f050029;
        public static final int disconnect_text=0x7f05002a;
        public static final int english=0x7f050009;
        public static final int german=0x7f050008;
        public static final int given_name=0x7f050005;
        public static final int hashcode=0x7f050013;
        public static final int help=0x7f050010;
        public static final int hint=0x7f05002b;
        public static final int info=0x7f05000f;
        public static final int language=0x7f050006;
        /**  SettingsView 
 SettingsView 
 SettingsView 
         */
        public static final int mobile_name=0x7f050004;
        public static final int name=0x7f05000a;
        public static final int no=0x7f05001c;
        public static final int no_items=0x7f050001;
        public static final int note_text=0x7f05000d;
        /**  Discovery Notificator 
 Discovery Notificator 
 Discovery Notificator 
         */
        public static final int note_title=0x7f05000c;
        public static final int ok=0x7f050016;
        /**  Connection settings Dialog 
 Connection settings Dialog 
 Connection settings Dialog 
         */
        public static final int pc_settings=0x7f050018;
        public static final int quit=0x7f050011;
        /**  Options Menu 
 Options Menu 
 Options Menu 
         */
        public static final int settings=0x7f05000e;
        /**  Help Dialog 
 Help Dialog 
 Help Dialog 
         */
        public static final int settings_label=0x7f050021;
        public static final int settings_text1=0x7f050022;
        public static final int settings_text2=0x7f050023;
        public static final int thanks=0x7f05002c;
        public static final int too_short=0x7f05000b;
        public static final int version=0x7f05001e;
        /**  About Dialog 
 About Dialog 
 About Dialog 
         */
        public static final int version_label=0x7f05001d;
        public static final int waiting=0x7f050003;
        /**  Disconnect Dialog 
 Disconnect Dialog 
 Disconnect Dialog 
         */
        public static final int warning=0x7f050019;
        public static final int warning_disconnect=0x7f05001a;
        public static final int website=0x7f050020;
        public static final int yes=0x7f05001b;
    }
}
